server:
  address: 127.0.0.1
  port: 10000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master #默认git分支
          search-paths: config #git仓库地址下的相对搜索地址（可用使用通配符）可以配置多个 用,分割。
          uri: https://github.com/jiejiedeai/config-server-properties.git
          username: 501220307@qq.com
          password: Qp045692
eureka:
  instance:
    appname: ${spring.application.name}  #在eureka服务上注册的应用程序组的名字，默认为unknow
    non-secure-port: ${server.port:80} #获取该实例应该接收通信的非安全端口。默认为80
    prefer-ip-address: true  #将ip注册到eureka不用主机名
    lease-renewal-interval-in-seconds: 3 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30秒
    LeaseExpirationDurationInSeconds: 5 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    metadata-map: #获取与此实例相关联的元数据(key,value)。这个信息被发送到eureka服务器，其他实例可以使用。
      instanceId: instanceId:${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
        #defaultZone中填写的URL必须包括后缀/eureka，否则各eureka server之间不能通信
        #defaultZone为默认的Zone，来源于AWS的概念。区域（Region）和可用区（Availability Zone,AZ）是AWS的另外两个概念。区域是指服务器所在的区域，
        #比如北美洲、南美洲、欧洲和亚洲等，每个区域一般由多个可用区组成。 在本案例中defaultZone是指Eureka Server的注册地址。